name: CI

on: [push]

jobs: 
  build: 

    runs-on: ubuntu-lastest

    steps: 
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run s multi-line script
      run: 
        echo Add other action to build, 
        echo test, and deploy your project.
      
